
### Create - Cadastrar
POST https://localhost:5001/api/carro/entradadecarro
Content-Type: application/json

{
    "Modelo" : "Carro do maicon",
    "Placa" : "bbc-666",
    "Cor" : "Roxo" 
}

### Read - Listar
GET https://localhost:5001/api/carro/relacaodecarros

### Buscar - Buscar por Id
GET https://localhost:5001/api/carro/buscarporcarroid/2

### Buscar - Buscar por Placa
GET https://localhost:5001/api/carro/bucasrporplaca/bbc-666

### Update - Atualizar por Id
PUT https://localhost:5001/api/carro/atualizarporcarroid
Content-Type: application/json

{
    "CarroId" :  3,
    "Modelo" : "Mercedes",
    "Placa" : "ooo-0001",
    "Cor" : "preto" 
}

### Delete - Excluir por Id
DELETE https://localhost:5001/api/carro/removerporcarroid/3

### Delete - Excluir por Placa
DELETE https://localhost:5001/api/carro/removerporcarroplaca/abc-123
