###Create - Cadastrar
POST https://localhost:5001/api/pessoa/novapessoa
Content-Type: application/json

{
    "Nome" : "Pedro",
    "Cpf" : "2222",
    "Telefone" : "2222"
}

### Read - Listar
GET https://localhost:5001/api/pessoa/listapessoas

### Buscar - Buscar por Cpf
GET https://localhost:5001/api/pessoa/buscarcpf/111

### Update - Atualizar por Id
PUT https://localhost:5001/api/pessoa/atualizarpessoa
Content-Type: application/json

{
    "PessoaId" :  1,
    "Nome" : "Carlos",
    "Cpf" : "333",
    "Telefone" : "888" 
}

### Delete - Excluir por Cpf
DELETE https://localhost:5001/api/pessoa/removerpessoacpf/333



