### Create - Atualizar por Id
POST  https://localhost:5001/api/saida/saida
Content-Type: application/json

{   
     "SaidaId" : 1,
    "PessoaId" : 1,
    "CarroId" : 1
}



### Read - Listar
GET https://localhost:5001/api/saida/listasaida


