###Iniciando - criar
POST https://localhost:5001/api/vaga/inicial

###Create - criar
POST https://localhost:5001/api/vaga/novavaga
Content-Type: application/json

{
    "Status" : "Livre",
    "Tipo" : "Carro"
}

### Read - Listar
GET https://localhost:5001/api/vaga/listavagas


### Update - Atualizar por Id
PUT https://localhost:5001/api/vaga/atualizarvaga
Content-Type: application/json

{   
    "VagaId" : 1,
    "status" : "ocupado"
}

