###Create - criar
POST https://localhost:5001/api/vaga/novavaga
Content-Type: application/json

{
    "Status" : false,
    "Tipo" : 15
}

### Read - Listar
GET https://localhost:5001/api/vaga/relacaodevagas

### Buscar - Buscar por iD
GET https://localhost:5001/api/vaga/buscarporvagaid/6


### Update - Atualizar por Id
PUT https://localhost:5001/api/vaga/atualizarporvagaid
Content-Type: application/json

{   
    "VagaId" : 2,
    "Status" : true,
    "Tipo" : 27 
}

### Delete - Excluir por Id
DELETE https://localhost:5001/api/vaga/removerporvagaid/2

